export const  config = {
    editor_auth_token: "ce1e9209-c8ae-4f75-b96c-c4c116dfa90e",
    spa_regex: "editor.coupomated.com",
    api_url: "https://editor.coupomated.com/api/editor",
    image_url: "https://editor.coupomated.com/storage/",
    spa_url:
      "https://editor.coupomated.com/editor/data/merchant/coupons?editor_token=",
    create_coupon:
      "https://editor.coupomated.com/editor/data/create-coupon?merchant_id=",
    live_coupons: "https://editor.coupomated.com/editor/data/live/coupons/",
    view_editor_dashboard: "https://editor.coupomated.com/editor/data/index",
    admin_panel_dashboard: "https://editor.coupomated.com/",
    version: "1.1.4",
    release_date: "21st July, 2023",
    affiliate_params: [
      "utm_source",
      "utm_medium",
      "utm_terms",
      "utm_campaign",
      "admitad_uid",
      "tagtag_uid",
      "ie",
      "linkCode",
      "tag",
      "ascsubtag",
      "linkId",
      "bbn",
      "offer_id",
      "aff_id",
      "aff_click_id",
      "Lead",
      "CPL",
      "CPR",
      "Lead",
      "CPI",
      "CPT",
      "CPA",
      "cancel",
      "Closed",
      "Paused",
      "insurance",
      "Campaigns",
      "Marketing",
      "PPC",
      "Casino",
      "Incent",
      "CPV",
      "Revshare",
      "Survey",
      "lead",
      "WW",
      "Test",
      "pf_rd_m",
      "pf_rd_s",
      "pf_rd_r",
      "pf_rd_p",
      "pf_rd_i",
      "ref",
      "pf_rd_t",
      "aid",
      "node",
      "language",
    ],
    coupon_rejection_keywords: ["CD"],
  };
  